services:
  web:
    image: node:21
    ports:
      - $APP_PORT:$APP_PORT
    expose:
      - $APP_PORT
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DB_HOST=db
      - MONGO_URL=mongodb://mongo
    depends_on:
      - db
      - mongo
    entrypoint: ["npm", "run", "${APP_ENV}:docker"]

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - 5432:5432
    expose:
      - 5432

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017

  adminer:
    build:
      context: ./docker
      dockerfile: adminer_mongodb.Dockerfile
    ports:
      - 8080:8080

volumes:
  postgres_data:
  mongo_data: